env:
  browser: true
  es2021: true
plugins:
  - '@typescript-eslint'
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
rules:
  i18n-text/no-en: 'off'
  no-restricted-syntax:
    - error
    - selector: TSEnumDeclaration
      message: Don't declare enums.
  prettier/prettier: 'off'
  no-mixed-operators: error
  '@typescript-eslint/prefer-readonly': error
  '@typescript-eslint/prefer-readonly-parameter-types':
    - error
    - ignoreInferredTypes: true
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
  # See https://zenn.dev/teppeis/articles/2023-04-typescript-5_0-verbatim-module-syntax for enabling reason
  '@typescript-eslint/consistent-type-imports': 'error'
  '@typescript-eslint/no-import-type-side-effects': 'error'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
