[config]
skip_core_tasks = true

[tasks.lint]
category = "Tools"
description = "Run linters and formatters without changes"
dependencies = [
  { name = "build", path = "./bin/cli" },
]
script = [
  "dprint check",
  "crystal tool format --check",
  "./bin/ameba",
  "./bin/cli lint",
]

[tasks.lint-fix]
category = "Tools"
description = "Run linters and formatters with changes"
script = [
  "dprint fmt",
  "crystal tool format",
  "./bin/ameba --fix"
]

[tasks.test]
category = "Tools"
description = 'Run tests'
script = [
	'npx tsc',
	'npx ts-node-test test/*.ts',
	'crystal spec'
]

[tasks.check]
category = "Tools"
description = 'Should pass before merging PR'
dependencies = [
  "lint",
  "test",
]

[tasks.setup]
category = "Tools"
description = 'Install dependencies'
run_task = [
  { name = "install_asdf_dependencies" },
  { name = "install_crystal_dependencies" },
  { name = "install_ecmascript_dependencies" },
  { name = "build" },
]

[tasks.help]
category = "Tools"
description = 'Might help you - (This one)'
script = [
  'makers --list-category-steps Tools',
]

[tasks.install_asdf_dependencies]
category = "Sub"
description = 'Install asdf managed dependencies'
# Neede some git-url style because they are not yet registered.
script = [
  # https://github.com/asdf-vm/asdf-plugins/pull/693
  '(asdf plugin-list | grep cargo-make) || asdf plugin-add cargo-make https://github.com/kachick/asdf-cargo-make.git',
  # https://github.com/asdf-vm/asdf-plugins/pull/691
  '(asdf plugin-list | grep dprint) || asdf plugin-add dprint https://github.com/asdf-community/asdf-dprint',
  '(asdf plugin-list | grep crystal) || asdf plugin-add crystal',
  '(asdf plugin-list | grep nodejs) || asdf plugin-add nodejs',
  'asdf install',
]

[tasks.install_crystal_dependencies]
category = "Sub"
description = 'Install shards managed dependencies'

[tasks.install_ecmascript_dependencies]
category = "Sub"
description = 'Install dependencies for TypeScript'

[tasks.build]
category = "Tools"
description = 'Compile CLI'
script = [
	'mkdir -p ./bin',
	'crystal build ./src/cli.cr -o ./bin/cli',
]

[tasks.validate]
category = "Tools"
description = 'Run renovate official validator'
dependencies = [
  { name = "cli", path = "./bin/cli" },
]
script = [
  './bin/cli validate',
]

[tasks.release]
category = "Tools"
description = 'Adjust and tagged for stable versions'
dependencies = [
  { name = "cli", path = "./bin/cli" },
]
script = [
  './bin/cli release --version=$1',
]

[tasks.scaffold]
category = "Tools"
description = 'Generate base files for new plugin'
dependencies = [
  { name = "cli", path = "./bin/cli" },
]
script = [
  './bin/cli scaffold --plugin=$1',
  'dprint fmt'
]

