name: CI - Crystal
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-crystal.yml'
      - 'spec/**'
      - 'src/**'
      - 'shard.yml'
      - 'shard.lock'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - '.github/workflows/ci-crystal.yml'
      - 'spec/**'
      - 'src/**'
      - 'shard.yml'
      - 'shard.lock'
      - 'package.json'
      - 'package-lock.json'

jobs:
  asdf-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: kachick/action-parse-asdf-tool-versions@v1
        id: parse
    outputs:
      tool-versions: '${{ steps.parse.outputs.json }}'
  spec:
    needs: [asdf-parser]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).crystal }}'
      # Need node.js to install validator. Spec includes the validator runner
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).nodejs }}'
          cache: npm
      - run: npm ci
      - run: crystal spec
