name: CI - Crystal
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-crystal.yml'
      - '**/*.cr'
      - '**/*.ecr'
      - 'shard.yml'
      - 'shard.lock'
      - '.ameba.yml'
      - '.tool-versions'
  pull_request:
    paths:
      - '.github/workflows/ci-crystal.yml'
      - '**/*.cr'
      - '**/*.ecr'
      - 'shard.yml'
      - 'shard.lock'
      - '.ameba.yml'
      - '.tool-versions'

jobs:
  spec:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: '1.9.2' # selfup { "regex": "\\d[^']+", "script": "crystal --version | head -n 1 | cut -d ' ' -f 2" }
          shards: '0.17.4' # selfup { "regex": "\\d[^']+", "script": "shards --version | cut -d ' ' -f 2" }
      # Need node.js to install validator. Spec includes the validator runner
      - run: crystal spec --tag '~needs_npm'
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Crystal Ameba Linter
        # Accepts to be different with nixpkgs's ameba, use latest by renovatebot
        uses: crystal-ameba/github-action@v0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
