name: CI - Crystal
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-crystal.yml'
      - '**/*.cr'
      - '**/*.ecr'
      - 'shard.yml'
      - 'shard.lock'
      - '.tool-versions'
  pull_request:
    paths:
      - '.github/workflows/ci-crystal.yml'
      - '**/*.cr'
      - '**/*.ecr'
      - 'shard.yml'
      - 'shard.lock'
      - '.tool-versions'

jobs:
  spec:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).crystal }}'
      # Need node.js to install validator. Spec includes the validator runner
      - run: crystal spec --tag '~needs_npm'
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache ameba
        id: cache
        uses: actions/cache@v3
        with:
          path: ./bin/ameba
          key: ameba-${{ runner.os }}-crystal_${{ fromJson(needs.asdf-parser.outputs.tool-versions).crystal }}-${{ hashFiles('shard.lock') }}
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).crystal }}'
      - run: shards install
        if: steps.cache.outputs.cache-hit != 'true'
      - run: make crystal-lint-check
