name: CI - Crystal
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-crystal.yml'
      - '**/*.cr'
      - '**/*.ecr'
      - 'shard.yml'
      - 'shard.lock'
      - '.tool-versions'
  pull_request:
    paths:
      - '.github/workflows/ci-crystal.yml'
      - '**/*.cr'
      - '**/*.ecr'
      - 'shard.yml'
      - 'shard.lock'
      - '.tool-versions'

jobs:
  spec:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
        with:
          # Keep same version as used in *.nix
          crystal: '1.8.2'
          shards: '0.17.3'
      # Need node.js to install validator. Spec includes the validator runner
      - run: crystal spec --tag '~needs_npm'
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache ameba
        id: cache
        uses: actions/cache@v3
        with:
          path: ./bin/ameba
          key: ameba-${{ runner.os }}-crystal_1.8.2-${{ hashFiles('shard.lock') }}
      - uses: crystal-lang/install-crystal@v1
        with:
          # Keep same version as used in *.nix
          crystal: '1.8.2'
          shards: '0.17.3'
      - run: shards install
        if: steps.cache.outputs.cache-hit != 'true'
      - run: make crystal-lint-check
