name: CI - Crystal
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-crystal.yml'
      - '**/*.cr'
      - '**/*.ecr'
      - 'shard.yml'
      - 'shard.lock'
      - '.tool-versions'
  pull_request:
    paths:
      - '.github/workflows/ci-crystal.yml'
      - '**/*.cr'
      - '**/*.ecr'
      - 'shard.yml'
      - 'shard.lock'
      - '.tool-versions'

jobs:
  asdf-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: kachick/action-parse-asdf-tool-versions@v1
        id: parse
    outputs:
      tool-versions: '${{ steps.parse.outputs.json }}'
  spec:
    needs: [asdf-parser]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).crystal }}'
      # Currently shards is unused except ameba
      # - run: shards install
      # Need node.js to install validator. Spec includes the validator runner
      - run: crystal spec --tag '~needs_npm'
  lint:
    needs: [asdf-parser]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache ameba
        id: cache
        uses: actions/cache@v3
        with:
          path: ./bin/ameba
          key: ${{ runner.os }}-${{ hashFiles('shard.lock') }}-ameba
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).crystal }}'
      - run: shards install
        if: steps.cache.outputs.cache-hit != 'true'
      - run: make crystal-lint-check
