name: CI - Development Environment
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-dev.yml'
      - '*.nix'
      - 'Makefile'
  pull_request:
    paths:
      - '.github/workflows/ci-dev.yml'
      - '*.nix'
      - 'Makefile'
  schedule:
    # About JST 8:00
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  parse:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      current: ${{ steps.current.outputs.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Install nix parser
        run: curl -L https://github.com/kachick/nix-headbump/releases/download/v0.2.0/nix-headbump_Linux_x86_64.tar.gz | tar xvz -C ./ nix-headbump
      - run: ./nix-headbump --version
      - id: current
        run: |
          ref="$(./nix-headbump detect --current)"
          echo "ref=${ref}" | tee -a "$GITHUB_OUTPUT"
  tasks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [parse]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/${{ needs.parse.outputs.current }}.tar.gz
      - run: nix-build
      - run: nix-shell --run 'make setup'
      - name: Log current versions
        run: nix-shell --run 'make versions'
      - name: Run linters
        run: nix-shell --run 'make check'
