name: CI - Official
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-official.yml'
      - 'src/renovate_config_asdf/github_actions_helper.cr'
      - 'plugins/*.json5'
      - 'package.json'
      - 'package-lock.json'
      - 'default.json'
      - 'renovate.json'
      - 'self.json'
      - '.tool-versions'
  pull_request:
    paths:
      - '.github/workflows/ci-official.yml'
      - 'src/renovate_config_asdf/github_actions_helper.cr'
      - 'plugins/*.json5'
      - 'package.json'
      - 'package-lock.json'
      - 'default.json'
      - 'renovate.json'
      - 'self.json'
      - '.tool-versions'

jobs:
  asdf-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: kachick/action-parse-asdf-tool-versions@v1
        id: parse
    outputs:
      tool-versions: '${{ steps.parse.outputs.json }}'

  build-cli:
    needs: [asdf-parser]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).crystal }}'
      - run: shards install
      - run: make build-tools
      - uses: actions/upload-artifact@v3
        with:
          name: cli
          path: ./bin/cli

  set-matrix:
    needs: [build-cli]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    outputs:
      configs: ${{ steps.set-matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p ./bin
      - uses: actions/download-artifact@v3
        with:
          name: cli
          path: ./bin/
      - id: set-matrix
        run: echo "json_array=$(git ls-files 'plugins' 'default.json' 'renovate.json' | ./bin/cli generate_matrix --matrix_chunk_size=10)" >> "$GITHUB_OUTPUT"

  validate:
    needs: [set-matrix, asdf-parser, build-cli]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        chunked_plugins: ${{fromJson(needs.set-matrix.outputs.json_array)}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).nodejs }}'
          cache: npm
      - run: npm ci # `--ignore-scripts` do not cover RE2
      - run: ./bin/cli validate --globs='${{ matrix.chunked_plugins }}'
