name: CI - Official
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-official.yml'
      - 'plugins/*.json5'
      - 'package.json'
      - 'package-lock.json'
      - 'default.json'
      - 'renovate.json'
      - 'self.json'
      - '.tool-versions'
  pull_request:
    paths:
      - '.github/workflows/ci-official.yml'
      - 'plugins/*.json5'
      - 'package.json'
      - 'package-lock.json'
      - 'default.json'
      - 'renovate.json'
      - 'self.json'
      - '.tool-versions'

jobs:
  asdf-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: kachick/action-parse-asdf-tool-versions@v1
        id: parse
    outputs:
      tool-versions: '${{ steps.parse.outputs.json }}'
  set-matrix:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    outputs:
      configs: ${{ steps.set-matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          config_by_line=$(git ls-files 'plugins' 'default.json' 'renovate.json')
          configs=$(jq -cnM --arg var "$config_by_line" '$var|split("\n")')
          echo "::set-output name=value::${configs}"

  validate:
    needs: [set-matrix, asdf-parser]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        config: ${{fromJson(needs.set-matrix.outputs.configs)}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).nodejs }}'
          cache: npm
      - run: npm ci # `--ignore-scripts` do not cover RE2
      - run: RENOVATE_CONFIG_FILE=${{ matrix.config }} npx renovate-config-validator
