name: CI - Official
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-official.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'default.json'
      - 'renovate.json'
      - 'self.json'
      - '.tool-versions'
  pull_request:
    paths:
      - '.github/workflows/ci-official.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'default.json'
      - 'renovate.json'
      - 'self.json'
      - '.tool-versions'

jobs:
  asdf-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: kachick/action-parse-asdf-tool-versions@v1
        id: parse
    outputs:
      tool-versions: '${{ steps.parse.outputs.json }}'

  validate:
    needs: [asdf-parser]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).nodejs }}'
          cache: npm
      - run: npm ci # `--ignore-scripts` do not cover RE2
      # renovate.json will always tested by the CLI
      - run: RENOVATE_CONFIG_FILE=default.json npx renovate-config-validator
      - run: RENOVATE_CONFIG_FILE=self.json npx renovate-config-validator
