name: CI - .tool-versions
on:
  pull_request:
    paths:
      - 'examples/.tool-versions'

jobs:
  installable:
    if: ${{ github.actor == 'renovate[bot]' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - run: git fetch origin ${{ github.base_ref }} --depth=1
      - name: Install gh-action-multiline
        run: curl -fsSL https://raw.githubusercontent.com/kachick/gh-action-multiline/main/scripts/install-in-github-action.sh | sh -s v0.1.1
      - name: Re-format only changed .tool-versions
        id: format-only-new-versions
        # Do not use `echo json=$(script)` syntax here. The script generates multilines.
        run: |
          targets="$(mktemp)"
          git diff origin/${{ github.base_ref }} HEAD --word-diff --relative ./examples/.tool-versions | \
            grep -F ']{+' | grep -vP 'haskell|php' | ruby -e 'puts STDIN.each_line.map { |l| /\A(\S+\s+).*?\{\+([^\+]+)/.match(l).captures.join }.join("\n")' > "$targets"


          gh-action-multiline -name=lines < "$targets" | tee -a "$GITHUB_OUTPUT"
          grep -P '\S' "$targets" || echo 'skip_install=true' | tee -a "$GITHUB_OUTPUT"

      - uses: asdf-vm/actions/install@v2
        if: steps.format-only-new-versions.outputs.skip_install != 'true'
        with:
          tool_versions: |
            ${{ steps.format-only-new-versions.outputs.lines }}
