name: CI - .tool-versions
on:
  pull_request:
    paths:
      - 'examples/.tool-versions'

jobs:
  installable:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - id: format-only-new-versions
        # Do not use `echo json=$(script)` syntax here. The script generates multilines.
        run: |
          echo 'json=' | tee --append $GITHUB_OUTPUT
          git diff origin/main HEAD --word-diff --relative ./examples/.tool-versions | grep -F ']{+' | ruby -r json -e 'puts STDIN.each_line.map { |l| /\A(\S+\s+).*?\{\+([^\+]+)/.match(l).captures.join }.join("\n").to_json' | tee --append $GITHUB_OUTPUT
      - uses: asdf-vm/actions/install@v1
        with:
          tool_versions: '${{ fromJson(steps.format-only-new-versions.outputs.json) }}'
