name: CI
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci.yml'
      - '**/*.json'
      - '!.vscode'
      - '**/*.json5'
      - 'spec/**'
      - 'scripts/validator.cr'
      - 'Makefile'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - '**/*.json'
      - '!.vscode'
      - '**/*.json5'
      - 'spec/**'
      - 'scripts/validator.cr'
      - 'Makefile'

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm install
      - uses: crystal-lang/install-crystal@v1
      - run: make test

  set-matrix:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    outputs:
      configs: ${{ steps.set-matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          config_by_line=$(git ls-files 'plugins' 'default.json' 'renovate.json')
          configs=$(jq -cnM --arg var "$config_by_line" '$var|split("\n")')
          echo "::set-output name=value::${configs}"

  validate:
    timeout-minutes: 5
    needs: [set-matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: ${{fromJson(needs.set-matrix.outputs.configs)}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      # npm ci --ignore-scripts do not cover RE2
      - run: npm install
      - run: RENOVATE_CONFIG_FILE=${{ matrix.config }} npx renovate-config-validator
