name: Lint - dprint
on:
  push:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
      - '.vscode'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '.vscode'
jobs:
  dprint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.2
        with:
          dprint-version: '0.34.5'
