name: Lint - definitions
on:
  push:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
      - '.vscode'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '.vscode'
      - '**/*.md'
jobs:
  asdf-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: kachick/action-parse-asdf-tool-versions@v1
        id: parse
    outputs:
      tool-versions: '${{ steps.parse.outputs.json }}'
  definitions:
    needs: [asdf-parser]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).crystal }}'
      - run: shards install --production
      - run: crystal run src/cli.cr -- lint
