name: Lint
on:
  push:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'LICENSE'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.1
