name: Lint - definitions
on:
  push:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
      - '.vscode'
      - '**/*.md'
      - '.github/workflows/ci-nix.yml'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '.vscode'
      - '**/*.md'
      - '.github/workflows/ci-nix.yml'
jobs:
  definitions:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
        with:
          # Keep same version as used in *.nix
          crystal: '1.9.2'
          shards: '0.17.3'
      - run: shards install --production
      - run: crystal run src/cli.cr -- lint
