name: Lint
on:
  push:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
      - '.vscode'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '.vscode'
jobs:
  asdf-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: kachick/action-parse-asdf-tool-versions@v1
        id: parse
    outputs:
      tool-versions: '${{ steps.parse.outputs.json }}'
  dprint:
    needs: [asdf-parser]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.1
        with:
          dprint-version: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).dprint }}'
  definitions:
    needs: [asdf-parser]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).crystal }}'
      # Currently shards is unused except ameba
      # - run: shards install
      - run: make build-tools
      - run: make lint-definitions
